/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcreCard {
    }
    interface AcreClock {
    }
}
declare global {
    interface HTMLAcreCardElement extends Components.AcreCard, HTMLStencilElement {
    }
    var HTMLAcreCardElement: {
        prototype: HTMLAcreCardElement;
        new (): HTMLAcreCardElement;
    };
    interface HTMLAcreClockElement extends Components.AcreClock, HTMLStencilElement {
    }
    var HTMLAcreClockElement: {
        prototype: HTMLAcreClockElement;
        new (): HTMLAcreClockElement;
    };
    interface HTMLElementTagNameMap {
        "acre-card": HTMLAcreCardElement;
        "acre-clock": HTMLAcreClockElement;
    }
}
declare namespace LocalJSX {
    interface AcreCard {
    }
    interface AcreClock {
    }
    interface IntrinsicElements {
        "acre-card": AcreCard;
        "acre-clock": AcreClock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acre-card": LocalJSX.AcreCard & JSXBase.HTMLAttributes<HTMLAcreCardElement>;
            "acre-clock": LocalJSX.AcreClock & JSXBase.HTMLAttributes<HTMLAcreClockElement>;
        }
    }
}
