import type { NextPage } from "next"
import Head from "next/head"
import s from "styles/index.module.scss"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${s.container}`}>Hello World!</div>
    </>
  )
}
export default Home
