import { schema } from './schema'

export const doc = schema.node('doc', null, [
  schema.node('heading', { level: 1 }, [schema.text("On First Looking into Chapman's Homer")]),
  schema.node('paragraph', null, [schema.text("Much have I travell'd in the realms of gold,")]),
  schema.node('paragraph', null, [schema.text('And many goodly states and kingdoms seen;')]),
  schema.node('paragraph', null, [schema.text('Round many western islands have I been')]),
  schema.node('paragraph', null, [schema.text('Which bards in fealty to Apollo hold.')]),
  schema.node('paragraph', null, [schema.text('Oft of one wide expanse had I been told')]),
  schema.node('paragraph', null, [schema.text('That deep-browed Homer ruled as his demesne;')]),
  schema.node('paragraph', null, [schema.text('Yet did I never breathe its pure serene')]),
  schema.node('paragraph', null, [schema.text('Till I heard Chapman speak out loud and bold:')]),
  schema.node('paragraph', null, [schema.text('Then felt I like some watcher of the skies')]),
  schema.node('paragraph', null, [schema.text('When a new planet swims into his ken;')]),
  schema.node('paragraph', null, [schema.text('Or like stout Cortez when with eagle eyes')]),
  schema.node('paragraph', null, [schema.text("He star'd at the Pacific  – and all his men")]),
  schema.node('paragraph', null, [schema.text("Look'd at each other with a wild surmise  – ")]),
  schema.node('paragraph', null, [schema.text('Silent, upon a peak in Darien.')]),

  schema.node('paragraph', null, [schema.text("Much have I travell'd in the realms of gold,")]),
  schema.node('paragraph', null, [schema.text('And many goodly states and kingdoms seen;')]),
  schema.node('paragraph', null, [schema.text('Round many western islands have I been')]),
  schema.node('paragraph', null, [schema.text('Which bards in fealty to Apollo hold.')]),
  schema.node('paragraph', null, [schema.text('Oft of one wide expanse had I been told')]),
  schema.node('paragraph', null, [schema.text('That deep-browed Homer ruled as his demesne;')]),
  schema.node('paragraph', null, [schema.text('Yet did I never breathe its pure serene')]),
  schema.node('paragraph', null, [schema.text('Till I heard Chapman speak out loud and bold:')]),
  schema.node('paragraph', null, [schema.text('Then felt I like some watcher of the skies')]),
  schema.node('paragraph', null, [schema.text('When a new planet swims into his ken;')]),
  schema.node('paragraph', null, [schema.text('Or like stout Cortez when with eagle eyes')]),
  schema.node('paragraph', null, [schema.text("He star'd at the Pacific  – and all his men")]),
  schema.node('paragraph', null, [schema.text("Look'd at each other with a wild surmise  – ")]),
  schema.node('paragraph', null, [schema.text('Silent, upon a peak in Darien.')]),

  schema.node('paragraph', null, [schema.text("Much have I travell'd in the realms of gold,")]),
  schema.node('paragraph', null, [schema.text('And many goodly states and kingdoms seen;')]),
  schema.node('paragraph', null, [schema.text('Round many western islands have I been')]),
  schema.node('paragraph', null, [schema.text('Which bards in fealty to Apollo hold.')]),
  schema.node('paragraph', null, [schema.text('Oft of one wide expanse had I been told')]),
  schema.node('paragraph', null, [schema.text('That deep-browed Homer ruled as his demesne;')]),
  schema.node('paragraph', null, [schema.text('Yet did I never breathe its pure serene')]),
  schema.node('paragraph', null, [schema.text('Till I heard Chapman speak out loud and bold:')]),
  schema.node('paragraph', null, [schema.text('Then felt I like some watcher of the skies')]),
  schema.node('paragraph', null, [schema.text('When a new planet swims into his ken;')]),
  schema.node('paragraph', null, [schema.text('Or like stout Cortez when with eagle eyes')]),
  schema.node('paragraph', null, [schema.text("He star'd at the Pacific  – and all his men")]),
  schema.node('paragraph', null, [schema.text("Look'd at each other with a wild surmise  – ")]),
  schema.node('paragraph', null, [schema.text('Silent, upon a peak in Darien.')])
])
